# -*- coding: utf-8 -*-
"""Scan Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIvoPaLF6iJRNI5yRrOEO5696MBjImIN
"""

import matplotlib.pyplot as plt

def direct_line(x1,y1,x2,y2):
  pixels = []
  print("\n ---Direct Line Equation Method--- ")
  print("Starting point: ",x1,y1)
  print("Ending point: ",x2,y2)
  dx = x2 - x1
  dy = y2 - y1

  #For only vertical line
  if dx==0:
    print("Case: Vertical Line.\n")
    print("Slope is undefined.\n")
    start_y = min(y1,y2)
    end_y = max(y1,y2)
    for y in range(start_y, end_y+1):
      pixels.append((x1,y))
      print(f"x={x1}, y={y}, pixels -> {(x1,y)}")

  else:
        m = dy/dx
        b = y1 - m*x1
        print("Slope:",m)
        print("Y-intercept:",b)

        if abs(m) <= 1:
          print("Case: Shallow Line.\n")
          start_x = min(x1,x2)
          end_x = max(x1,x2)
          for x in range(start_x, end_x+1):
            y = m*x+b
            round_y = round(y)
            pixels.append((x,round_y))
            print(f"x={x}, y={round_y}, pixels -> {(x,round_y)}")
        else:
          print("Case: Steep Line.\n")
          start_y = min(y1,y2)
          end_y = max(y1,y2)
          for y in range(start_y, end_y+1):
            x = (y-b)/m
            round_x = round(x)
            pixels.append((round_x,y))
            print(f"x={round_x}, y={y}, pixels -> {(round_x,y)}")
  return pixels

########## MAIN PROGRAM ##########

#Enter Coordinates

x1 = int(input("Enter x1: "))
y1 = int(input("Enter y1: "))
x2 = int(input("Enter x2: "))
y2 = int(input("Enter y2: "))

#Calling Function

pixels = direct_line(x1,y1,x2,y2)

#Display Functions

print(pixels)

## Plotting pixels ##

x_pixels = [p[0] for p in pixels]
y_pixels = [p[1] for p in pixels]

plt.figure(figsize=(8,6)) # Fixed figsize syntax

plt.plot(
    [x1,x2],
    [y1,y2],
    label = "Ideal Mathematical Line"
)

plt.scatter(
    x_pixels,
    y_pixels,
    s = 100,
    marker="s",
    color="red",
    label= "Generated Pixels"
)

plt.scatter(
    [x1,x2],
    [y1,y2],
    s = 150,
    marker="o",
    label= "End Points"
)

for x,y in pixels:
  plt.text(x + 0.08, y + 0.08, f"({x},{y})", fontsize=9) # Corrected text annotation


plt.xticks(range(min(x1,x2)-1,max(x1,x2)+2)) # Fixed plt.xsticks to plt.xticks
plt.yticks(range(min(y1,y2)-1,max(y1,y2)+2))



plt.xlim(min(x1,x2)-1,max(x1,x2)+1) # Fixed plt.xlim to plt.xlim
plt.ylim(min(y1,y2)-1,max(y1,y2)+1)
plt.grid(True)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Direct Line Equation Method")
plt.legend()
plt.show()

"""### DDA Line Algorithm Visualization"""

dda_pixels = dda_line(0, 0, 10, 5)

x1_dda, y1_dda, x2_dda, y2_dda = 0, 0, 10, 5

x_dda_pixels = [p[0] for p in dda_pixels]
y_dda_pixels = [p[1] for p in dda_pixels]

plt.figure(figsize=(8,6))

plt.plot(
    [x1_dda, x2_dda],
    [y1_dda, y2_dda],
    label = "Ideal Mathematical Line"
)

plt.scatter(
    x_dda_pixels,
    y_dda_pixels,
    s = 100,
    marker="s",
    color="red",
    label= "Generated Pixels"
)

plt.scatter(
    [x1_dda, x2_dda],
    [y1_dda, y2_dda],
    s = 150,
    marker="o",
    label= "End Points"
)

for x,y in dda_pixels:
  plt.text(x + 0.08, y + 0.08, f"({x},{y})", fontsize=9)


plt.xticks(range(min(x1_dda,x2_dda)-1,max(x1_dda,x2_dda)+2))
plt.yticks(range(min(y1_dda,y2_dda)-1,max(y1_dda,y2_dda)+2))



plt.xlim(min(x1_dda,x2_dda)-1,max(x1_dda,x2_dda)+1)
plt.ylim(min(y1_dda,y2_dda)-1,max(y1_dda,y2_dda)+1)
plt.grid(True)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("DDA Line Algorithm")
plt.legend()
plt.show()

"""### Bresenham's Line Algorithm Visualization"""

bresenham_line_pixels = bresenham_line(0, 0, 10, 5)

x1_bl, y1_bl, x2_bl, y2_bl = 0, 0, 10, 5

x_bl_pixels = [p[0] for p in bresenham_line_pixels]
y_bl_pixels = [p[1] for p in bresenham_line_pixels]

plt.figure(figsize=(8,6))

plt.plot(
    [x1_bl, x2_bl],
    [y1_bl, y2_bl],
    label = "Ideal Mathematical Line"
)

plt.scatter(
    x_bl_pixels,
    y_bl_pixels,
    s = 100,
    marker="s",
    color="red",
    label= "Generated Pixels"
)

plt.scatter(
    [x1_bl, x2_bl],
    [y1_bl, y2_bl],
    s = 150,
    marker="o",
    label= "End Points"
)

for x,y in bresenham_line_pixels:
  plt.text(x + 0.08, y + 0.08, f"({x},{y})", fontsize=9)


plt.xticks(range(min(x1_bl,x2_bl)-1,max(x1_bl,x2_bl)+2))
plt.yticks(range(min(y1_bl,y2_bl)-1,max(y1_bl,y2_bl)+2))



plt.xlim(min(x1_bl,x2_bl)-1,max(x1_bl,x2_bl)+1)
plt.ylim(min(y1_bl,y2_bl)-1,max(y1_bl,y2_bl)+1)
plt.grid(True)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Bresenham's Line Algorithm")
plt.legend()
plt.show()

"""### Bresenham's Circle Algorithm Visualization"""

bresenham_circle_pixels = bresenham_circle(0, 0, 5)

xc, yc, r = 0, 0, 5

x_bc_pixels = [p[0] for p in bresenham_circle_pixels]
y_bc_pixels = [p[1] for p in bresenham_circle_pixels]

plt.figure(figsize=(8,6))

plt.scatter(
    x_bc_pixels,
    y_bc_pixels,
    s = 100,
    marker="o",
    color="blue",
    label= "Generated Pixels"
)

# Plot the center of the circle
plt.scatter(
    xc,
    yc,
    s = 150,
    marker="x",
    color="red",
    label= "Center"
)

plt.gca().set_aspect('equal', adjustable='box') # Make sure the circle looks round

plt.xticks(range(xc - r - 1, xc + r + 2))
plt.yticks(range(yc - r - 1, yc + r + 2))

plt.xlim(xc - r - 1, xc + r + 1)
plt.ylim(yc - r - 1, yc + r + 1)
plt.grid(True)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Bresenham's Circle Algorithm")
plt.legend()
plt.show()