# -*- coding: utf-8 -*-
"""lab 1 -image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QuLe-QLoBR1hkCOUcrtT9S7OfDieJXGu
"""

#Translation
import cv2
import numpy as np
import matplotlib.pyplot as plt
image = cv2.imread('/content/images.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
h, w = image.shape[:2]
tx = 100
ty = 150
M = np.float32([
[1, 0, tx],
[0, 1, ty]
])
translated = cv2.warpAffine(image, M, (w, h))
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(translated)
plt.title("Translated Image")
plt.axis("off")
plt.show()

#Scaling
import cv2
import numpy as np
import matplotlib.pyplot as plt
image = cv2.imread('/content/images.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
h, w = image.shape[:2]
sx = 5
sy = 3
M = np.float32([
[sx, 0, 0],
[0, sy, 0]
])
scaled = cv2.warpAffine(image,M,(int(w * sx), int(h * sy)))
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(scaled)
plt.title("Scaled Image")
plt.axis("off")
plt.show()

#Rotation
import cv2
import matplotlib.pyplot as plt
image = cv2.imread('/content/images.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
h, w = image.shape[:2]
center = (w // 2, h // 2)
angle = 45
M = cv2.getRotationMatrix2D(center, angle, 1.0)
rotated = cv2.warpAffine( image, M, (w, h) )
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(rotated)
plt.title("Rotated Image - 45°")
plt.axis("off")
plt.show()

#Reflection for X and Y axis
import cv2
import matplotlib.pyplot as plt
image = cv2.imread('/content/images.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
reflected = cv2.flip(image, -1)
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(reflected)
plt.title("Reflection about X and Y axes")
plt.axis("off")
plt.show()

#Combined
import cv2
import numpy as np
import matplotlib.pyplot as plt
image = cv2.imread('/content/images.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
h, w = image.shape[:2]
tx, ty = 100, 50
M = np.float32([
[1, 0, tx],
[0, 1, ty]
])
translated = cv2.warpAffine(image, M, (w, h))
sx, sy = 5,2
M = np.float32([
[sx, 0, 0],
[0, sy, 0]
])
scaled = cv2.warpAffine(image,M,(int(w * sx), int(h * sy)))
center = (w // 2, h // 2)
angle = 45
M = cv2.getRotationMatrix2D(center, angle, 1.0)
rotated = cv2.warpAffine(image,M,(w, h))
reflected_x = cv2.flip(image, 0)
reflected_y = cv2.flip(image, 1)
sx_com, sy_com = 1.5, 2
scaled_com = cv2.resize(image,None,fx=sx_com,fy=sy_com)
h2, w2 = scaled_com.shape[:2]
center_com = (w2 // 2, h2 // 2)
M = cv2.getRotationMatrix2D(center_com,30,1.0)
rotated_com = cv2.warpAffine(scaled_com,M,(w2, h2))
x_com, ty_com = 50, 30
M = np.float32([
[1, 0, tx],
[0, 1, ty]
])
transformed_com = cv2.warpAffine(rotated_com,M,(w2 + tx, h2 + ty))
plt.figure(figsize=(16, 12))
plt.subplot(2, 3, 1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")
plt.subplot(2, 3, 2)
plt.imshow(translated)
plt.title("Translated Image")
plt.axis("off")
plt.subplot(2, 3, 3)
plt.imshow(scaled)
plt.title("Scaled Image")
plt.axis("off")
plt.subplot(2, 3, 4)
plt.imshow(rotated)
plt.title("Rotated Image - 45°")
plt.axis("off")
plt.subplot(2, 3, 5)
plt.imshow(reflected_x)
plt.title("Reflection about X-axis")
plt.axis("off")
plt.subplot(2, 3, 6)
plt.imshow(reflected_y)
plt.title("Reflection about Y-axis")
plt.axis("off")
plt.tight_layout()
plt.show()